### ISSUE TITLE
Unexpected behaviour for a conflicting Ruby gem with no version specified

### ISSUE THREAD

**Issue by jacobpgn** [gocardless/bump-core#34]
For a Gemfile like this:
```
gem "rails", "4.2.7.1"
gem "web-console"
```

bump attempted to bump web-console (Gemfile.lock has 3.3.0) to 3.5.1, but could not as it requires rails >= 5. Instead, it updated web-console's dependencies and opened a confusing PR!

```
commit (origin/bump_web-console_to_3.5.1)
    Bump web-console to 3.5.1

    Bumps [web-console](https://github.com/rails/web-console) to 3.5.1.
    - [Release notes](https://github.com/rails/web-console/releases/tag/v3.5.1)
    - [Changelog](https://github.com/rails/web-console/blob/master/CHANGELOG.markdown)
    - [Commits](https://github.com/rails/web-console/compare/v3.3.0...v3.5.1)

diff --git a/Gemfile.lock b/Gemfile.lock
-    debug_inspector (0.0.2)
+    debug_inspector (0.0.3)
```

**Comment by greysteil** [comment]
This is the fault of the `UpdatCheckers` class (for Ruby). It doesn't check constraints (from other gems) when looking for the latest version of the gem it's trying to bump.

Two potential solutions:
1) Make update checkers smart
2) Put a check in the `DependencyFileUpdaters` class that the desired gem was actually bumped

Feels like 1) is definitely the way to go, but doing so probably means the `UpdateCheckers` and `DependencyFileUpdaters` classes become very similar - might make more sense just to merge them, and have the functionality currently in update checkers (i.e., get the very latest version) as a short-circuit where possible. So I think I prefer:

3) Merge the `UpdatCheckers` and `DependencyFileUpdaters` classes

@hmac / @jacobpgn - thoughts?

**Comment by jacobpgn** [comment]
It's still useful to bump the dependency's dependencies though, would be nice to preserve that effect! Would it be reasonable to open a "bump web-console's dependencies" PR in this scenario instead?

**Comment by greysteil** [comment]
(FYI, I'm working on this now. It's a big one, so will take a while.)

**Comment by greysteil** [comment]
@jacobpgn - agreed on bumping sub-dependencies, but if we're going to do that we ought to do it explicitly (by changing the parser classes to pull them out, after which they'll thread through the rest of the process normally). That one feels like it might need a setting - volume of PRs could get very high...

Or maybe having PRs like the one you've mentioned wouldn't be such a bad shout, either. Would be achieved by by ignoring the results of `needs_update`.

Either way, let's get this bug fixed first!
